name: beautiful_destinations
description: A mock of the beautiful destinations app
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

# flutter pub run build_runner build --delete-conflicting-outputs
environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  dio: ^4.0.0
  bloc: ^8.1.0
  intl: ^0.17.0
  badges: ^2.0.3
  retrofit: ^3.0.1
  equatable: ^2.0.5
  timelines: ^0.1.0
  share_plus: ^6.3.0
  like_button: ^2.0.5
  flutter_svg: ^1.1.6
  flutter_bloc: ^8.1.1
  url_launcher: ^6.1.6
  auto_size_text: ^3.0.0
  json_annotation: ^4.5.0
  cupertino_icons: ^1.0.2
  flutter_blurhash: ^0.7.0
  dropdown_button2: ^1.9.2
  json_serializable: ^6.2.0
  scroll_snap_list: 
    path: dependencies/scroll_snap_list
  # font_awesome_flutter: ^10.2.1

  dart_vlc: ^0.4.0
  video_player: ^2.4.8
  video_player_win: ^1.1.0
  video_player_macos: 1.0.6

dev_dependencies:
  retrofit_generator: any
  build_runner: 
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  generate: true
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/logo_black.svg
    - assets/images/logo_inline_black.svg
    - assets/images/logo_white.svg
    - assets/images/logo_inline_white.svg
    - assets/images/heart_solid.svg
    - assets/images/sliders.svg
    - assets/images/plane_departure_solid.svg
    - assets/mock/
    - assets/mock-hq/
    - assets/mock-lq/

  fonts:
    - family: manrope
      fonts:
        - asset: assets/fonts/manrope/manrope_extra_light.ttf
          weight: 200
        - asset: assets/fonts/manrope/manrope_light.ttf
          weight: 300
        - asset: assets/fonts/manrope/manrope_regular.ttf
          weight: 400
        - asset: assets/fonts/manrope/manrope_medium.ttf
          weight: 500
        - asset: assets/fonts/manrope/manrope_semi_bold.ttf
          weight: 600
        - asset: assets/fonts/manrope/manrope_bold.ttf
          weight: 700
        - asset: assets/fonts/manrope/manrope_extra_bold.ttf
          weight: 800
          # style: italic